os:
    - linux
    - osx

install:
    - if [ -f /etc/debian_version ]; then sudo make install_kcov; fi
    - if [ -f /etc/debian_version ]; then sudo make install_shells; fi

script:
    - if [ -f /etc/debian_version ]; then make alltest; fi
    - if [ -f /etc/debian_version ]; then make coveralls; fi
    - if uname | grep Darwin; then make unixtest; fi
